config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resources :reviews
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @books = Book.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @books = Book.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def show
    if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rating).round(2)
    end
  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @book = current_user.books.build(book_params)
    @book.category_id = params[:category_id]

    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @book.category_id = params[:category_id]
    if @book.update(book_params)
      redirect_to book_path
    else
      render 'edit'
    end

  end

  def destroy
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
  end

  def find_book
    @book = Book.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end

  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

  def review_params
      params.require(:review).permit(:rating, :comment)
  end

  def find_book
    @book = Book.find(params[:book_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => {:multipart => true } do |f| %>

  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  <%= f.file_field :book_img%>
  <%= f.input :title , label: "Book title" %>
  <%= f.input :description  %>
  <%= f.input :author %>
  <%= f.button :submit  %>
<% end %>

app/views/books/edit.html.erb
<h1> Edit Book <h1>

<%= simple_form_for @book, :html => {:multipart => true } do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.file_field :book_img%>
  <%= f.input :title , label: "Book title" %>
  <%= f.input :description  %>
  <%= f.input :author %>
  <%= f.button :submit  %>
<% end %>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category]%></h1>

<% if @books.count == 0 %>
  <h1> There is no books currently  in this category </h1>
<%else%>

  <div class="row">

  </div>

  <% @books.each do |book| %>

    <div class="col-md-3">
      <a href="/books/<%= book.id %>">
        <%= image_tag book.book_img.url(:book_index), class: "book" %>
      </a>

    </div>


  <% end %>
<%end%>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">

  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show) , class: "book-show"%>
  </div>

  <div class="col-md-8">
    <h2> <%= @book.title %> </h2>
    <h3> <%= @book.author %> </h3>
    <h2>Average Rating</h2>
    <div class="average-review-rating" data-score=<%= @average_review %>></div>
    <p> <%= @book.description %> </p>
  </div>

</div>

<div class="row">
  <div class="col-md-4">
      <!-- Where reviews/ratings will go-->
      <%= render @book.reviews %>
      <div>
        <%= link_to "Add review" , new_book_review_path(@book)%>
      </div>
  </div>
</div>


<%= link_to "Back", root_path %>

<% if user_signed_in? %>
  <% if @book.user_id == current_user.id %>
    <%= link_to "Edit", edit_book_path(@book) %>
    <%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
<% end %>

<script>
 $('.review-rating').raty({
   readOnly: true,
   score: function(){
     return $(this).attr('data-score')
   },
   path: '/assets/'
 });
</script>

<script>
  $('#rating-form').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).attr('data-score')
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default" >
      <div class="container">
        <div class ="navbar-header">
          <%= link_to "Book Review", root_path, class: "navbar-brand" %>
      </div>
      <ul class= "nav navbar-nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li> <%=  link_to"Sign Out", destroy_user_session_path, method: :delete %> </li>
          <%else%>
          <li> <%=  link_to"Log In", new_user_session_path %> </li>
        <% end %>
      </ul>

      <ul class="nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Add Book", new_book_path %></li>
        <% end %>

      </ul>

      <ul class="nav navbar-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" >Categories
              <spam class="caret"></spam>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% Category.all.each do |category |%>
                <li class="<%= 'active' if params[:category] == category.name%>">
                  <%= link_to category.name , books_path(category: category.name), class: "link" %>
                </li>
              <% end %>
            </ul>
        </li>
      </ul>

    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@book, @book.reviews.build]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<%end%>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<!--<p><%= review.rating %></p>-->
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in?%>
  <% if review.user_id == current_user.id %>
    <%= link_to "Edit" , edit_book_review_path(review.book, review)%>
    <%= link_to "Delete", book_review_path(review.book, review), method: :delete,
    data: {confim: "Are you sure?"} %>
  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@book, @review]) do|f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment%>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<h1>New Review<h1>

<%= render 'form'%>